IF DB_ID('PHANMEMTHITN') IS NULL CREATE DATABASE [PHANMEMTHITN]
GO

USE PHANMEMTHITN
GO

-- Bảng ROLE (Phân quyền)
CREATE TABLE ROLE
(
	MAROLE INT IDENTITY(1,1) PRIMARY KEY,
	TENROLE NVARCHAR(50) NOT NULL  -- 'Admin', 'GiangVien', 'SinhVien'
)
GO

-- Thêm dữ liệu mặc định cho ROLE
INSERT INTO ROLE (TENROLE) VALUES (N'Admin')
INSERT INTO ROLE (TENROLE) VALUES (N'GiangVien')
INSERT INTO ROLE (TENROLE) VALUES (N'SinhVien')
GO

-- Bảng NGUOIDUNG (User chung cho tất cả)
CREATE TABLE NGUOIDUNG
(
	ID INT IDENTITY(1,1),
	TENTAIKHOAN VARCHAR(15) PRIMARY KEY,
	MATKHAU VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100),
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE,
	MAROLE INT FOREIGN KEY REFERENCES ROLE(MAROLE)
)
GO

-- Thêm tài khoản Admin mặc định
INSERT INTO NGUOIDUNG (TENTAIKHOAN, MATKHAU, EMAIL, HOTEN, NGAYSINH, MAROLE) 
VALUES ('admin', '123456', 'admin@gmail.com', N'Administrator', '2000-01-01', 1)
GO

CREATE TABLE MONTHI
(
	IDMONTHI INT IDENTITY(1,1),
	MAMT VARCHAR(15) PRIMARY KEY,
	TENMT NVARCHAR(50),
	

)
GO

CREATE TABLE DANHMUCCAUHOI
(
	IDDANHMUC INT IDENTITY(1,1) PRIMARY KEY,
	MAMT VARCHAR(15) FOREIGN KEY REFERENCES MONTHI(MAMT) ON UPDATE CASCADE
)
GO


CREATE TABLE CAUHOI
(
	IDCAUHOI INT IDENTITY(1,1) PRIMARY KEY,
	NDCAUHOI NVARCHAR(500),
	DAPAN1 NVARCHAR NOT NULL, 
	DAPAN2 NVARCHAR NOT NULL,	
	DAPAN3 NVARCHAR NOT NULL,
	DAPAN4 NVARCHAR NOT NULL,
	DAPANDUNG NVARCHAR NOT NULL,
	IDDANHMUC INT FOREIGN KEY REFERENCES DANHMUCCAUHOI(IDDANHMUC) ON UPDATE CASCADE
)
GO

CREATE TABLE DETHI
(
	ID INT IDENTITY(1,1),
	MADETHI VARCHAR(10) PRIMARY KEY,
)
GO



CREATE TABLE KITHI
(
	ID INT IDENTITY(1,1),
	MAKITHI VARCHAR(10) PRIMARY KEY,
	TENKITHI NVARCHAR(50)
)
GO

CREATE TABLE CHITIETKITHI
(
	NGAYTHI DATE,
	THOIGIANTHI DATETIME,
)
GO


CREATE TABLE BANGDIEM
(
	ID INT IDENTITY(1,1),
	MABD VARCHAR(10) PRIMARY KEY,
	TENBD NVARCHAR(50),
)
GO
