// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhanMemThiTracNghiem.DAL.Model;

#nullable disable

namespace PhanMemThiTracNghiem.Migrations
{
    [DbContext(typeof(DuLieuDAL))]
    [Migration("20260103031142_database")]
    partial class database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.BANGDIEM", b =>
                {
                    b.Property<string>("MASV")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MAKITHI")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("MAMT")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CHITIETKYTHIMAKITHI")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("CHITIETKYTHIMAMT")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("CHITIETKYTHIMASV")
                        .HasColumnType("varchar(15)");

                    b.Property<double?>("DIEM")
                        .HasColumnType("float");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.HasKey("MASV", "MAKITHI", "MAMT");

                    b.HasIndex("CHITIETKYTHIMAKITHI", "CHITIETKYTHIMAMT", "CHITIETKYTHIMASV");

                    b.ToTable("BANGDIEM");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.CAUHOI", b =>
                {
                    b.Property<int>("MACAUHOI")
                        .HasColumnType("int");

                    b.Property<string>("DAPAN1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DAPAN2")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DAPAN3")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DAPAN4")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DAPANDUNG")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MAGV")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("MAMT")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("MONTHIMAMT")
                        .HasColumnType("varchar(40)");

                    b.Property<string>("NDCAUHOI")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("NGUOIDUNGID")
                        .HasColumnType("int");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.HasKey("MACAUHOI");

                    b.HasIndex("MONTHIMAMT");

                    b.HasIndex("NGUOIDUNGID");

                    b.ToTable("CAUHOI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.CHITIETDETHI", b =>
                {
                    b.Property<string>("MADETHI")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("MACAUHOI")
                        .HasColumnType("int");

                    b.Property<string>("DETHIMADETHI")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MUCDO")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MADETHI", "MACAUHOI");

                    b.HasIndex("DETHIMADETHI");

                    b.ToTable("CHITIETDETHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.CHITIETKYTHI", b =>
                {
                    b.Property<string>("MAKITHI")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("MAMT")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("MASV")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<double?>("DIEM")
                        .HasColumnType("float");

                    b.Property<int?>("NGUOIDUNGID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("THOIGIANBD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("THOIGIANKT")
                        .HasColumnType("datetime2");

                    b.Property<int?>("THOIGIANTHI")
                        .HasColumnType("int");

                    b.HasKey("MAKITHI", "MAMT", "MASV");

                    b.HasIndex("MAMT");

                    b.HasIndex("NGUOIDUNGID");

                    b.ToTable("CHITIETKYTHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.DETHI", b =>
                {
                    b.Property<string>("MADETHI")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("MAKITHI")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("MAMT")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("MONTHIMAMT")
                        .HasColumnType("varchar(40)");

                    b.HasKey("MADETHI");

                    b.HasIndex("MONTHIMAMT");

                    b.ToTable("DETHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.KITHI", b =>
                {
                    b.Property<string>("MAKITHI")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<string>("ADMIN")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<int?>("NGUOIDUNGID")
                        .HasColumnType("int");

                    b.Property<string>("TENKITHI")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("THOIGIANBDKITHI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("THOIGIANKTKITHI")
                        .HasColumnType("datetime2");

                    b.HasKey("MAKITHI");

                    b.HasIndex("NGUOIDUNGID");

                    b.ToTable("KITHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.MONTHI", b =>
                {
                    b.Property<string>("MAMT")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<int?>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TENMT")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MAMT");

                    b.ToTable("MONTHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.NGUOIDUNG", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HOTEN")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MAROLE")
                        .HasColumnType("int");

                    b.Property<string>("MATKHAU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("EMAIL")
                        .IsUnique();

                    b.HasIndex("MAROLE");

                    b.ToTable("NGUOIDUNG");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            EMAIL = "admin@gmail.com",
                            HOTEN = "Quản trị viên",
                            MAROLE = 1,
                            MATKHAU = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
                        });
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.ROLE", b =>
                {
                    b.Property<int>("MAROLE")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MAROLE"));

                    b.Property<string>("TENROLE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MAROLE");

                    b.ToTable("ROLE");

                    b.HasData(
                        new
                        {
                            MAROLE = 1,
                            TENROLE = "Admin"
                        },
                        new
                        {
                            MAROLE = 2,
                            TENROLE = "Giảng viên"
                        },
                        new
                        {
                            MAROLE = 3,
                            TENROLE = "Sinh viên"
                        });
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.BANGDIEM", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.CHITIETKYTHI", "CHITIETKYTHI")
                        .WithMany()
                        .HasForeignKey("CHITIETKYTHIMAKITHI", "CHITIETKYTHIMAMT", "CHITIETKYTHIMASV");

                    b.Navigation("CHITIETKYTHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.CAUHOI", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.MONTHI", null)
                        .WithMany("CAUHOI")
                        .HasForeignKey("MONTHIMAMT");

                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.NGUOIDUNG", null)
                        .WithMany("CAUHOI")
                        .HasForeignKey("NGUOIDUNGID");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.CHITIETDETHI", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.DETHI", null)
                        .WithMany("CHITIETDETHI")
                        .HasForeignKey("DETHIMADETHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.CHITIETKYTHI", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.MONTHI", null)
                        .WithMany("CHITIETKYTHI")
                        .HasForeignKey("MAMT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.NGUOIDUNG", null)
                        .WithMany("CHITIETKYTHI")
                        .HasForeignKey("NGUOIDUNGID");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.DETHI", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.MONTHI", "MONTHI")
                        .WithMany("DETHI")
                        .HasForeignKey("MONTHIMAMT");

                    b.Navigation("MONTHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.KITHI", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.NGUOIDUNG", null)
                        .WithMany("KITHI")
                        .HasForeignKey("NGUOIDUNGID");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.NGUOIDUNG", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.DAL.Model.ROLE", "ROLE")
                        .WithMany("NGUOIDUNG")
                        .HasForeignKey("MAROLE");

                    b.Navigation("ROLE");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.DETHI", b =>
                {
                    b.Navigation("CHITIETDETHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.MONTHI", b =>
                {
                    b.Navigation("CAUHOI");

                    b.Navigation("CHITIETKYTHI");

                    b.Navigation("DETHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.NGUOIDUNG", b =>
                {
                    b.Navigation("CAUHOI");

                    b.Navigation("CHITIETKYTHI");

                    b.Navigation("KITHI");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.DAL.Model.ROLE", b =>
                {
                    b.Navigation("NGUOIDUNG");
                });
#pragma warning restore 612, 618
        }
    }
}
