// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhanMemThiTracNghiem.Data;

#nullable disable

namespace PhanMemThiTracNghiem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260127141943_RemoveSoCauCoBanSoCauNangCaoFromCauTrucDe")]
    partial class RemoveSoCauCoBanSoCauNangCaoFromCauTrucDe
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.BaiThi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("DiemSo")
                        .HasColumnType("int")
                        .HasColumnName("diem_so");

                    b.Property<long?>("MaKyThi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_ky_thi");

                    b.Property<long?>("MaSinhVien")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_sinh_vien");

                    b.Property<DateTime?>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime?>("ThoiGianNopBai")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_nop_bai");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("MaKyThi");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("bai_thi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.CauHoiThi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MaMon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<long?>("NguoiTao")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("MaMon");

                    b.HasIndex("NguoiTao");

                    b.ToTable("cau_hoi_thi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.CauTrucDe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MaMon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_mon");

                    b.Property<long?>("MaNganHangDe")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_ngan_hang_de");

                    b.Property<int>("SoCau")
                        .HasColumnType("int")
                        .HasColumnName("so_cau");

                    b.HasKey("Id");

                    b.HasIndex("MaMon");

                    b.HasIndex("MaNganHangDe");

                    b.ToTable("cau_truc_de");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.KyThi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MaLop")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_lop");

                    b.Property<long?>("MaNganHangDe")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_ngan_hang_de");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenKyThi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_ky_thi");

                    b.Property<DateTime>("ThoiGianBatDau")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_bat_dau");

                    b.Property<DateTime>("ThoiGianKetThuc")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_ket_thuc");

                    b.Property<int>("ThoiLuongPhut")
                        .HasColumnType("int")
                        .HasColumnName("thoi_luong_phut");

                    b.Property<int?>("TongDiem")
                        .HasColumnType("int")
                        .HasColumnName("tong_diem");

                    b.Property<bool>("TronCauHoi")
                        .HasColumnType("bit")
                        .HasColumnName("tron_cau_hoi");

                    b.Property<bool>("TronDapAn")
                        .HasColumnType("bit")
                        .HasColumnName("tron_dap_an");

                    b.HasKey("Id");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaNganHangDe");

                    b.ToTable("ky_thi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LopHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_lop");

                    b.HasKey("Id");

                    b.ToTable("lop_hoc");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LopHocSinhVien", b =>
                {
                    b.Property<long>("MaLop")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_lop")
                        .HasColumnOrder(0);

                    b.Property<long>("MaSinhVien")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_sinh_vien")
                        .HasColumnOrder(1);

                    b.HasKey("MaLop", "MaSinhVien");

                    b.HasIndex("MaSinhVien");

                    b.ToTable("lop_hoc_sinh_vien");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LuaChonTracNghiem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("LaDapAnDung")
                        .HasColumnType("bit")
                        .HasColumnName("la_dap_an_dung");

                    b.Property<long?>("MaCauHoi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_cau_hoi");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.HasKey("Id");

                    b.HasIndex("MaCauHoi");

                    b.ToTable("lua_chon_trac_nghiem");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.MonHoc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("TenMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_mon");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.ToTable("mon_hoc");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NganHangDe", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MaMon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_mon");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<long?>("NguoiTao")
                        .HasColumnType("bigint")
                        .HasColumnName("nguoi_tao");

                    b.Property<string>("TenDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_de");

                    b.Property<int>("TongSoCau")
                        .HasColumnType("int")
                        .HasColumnName("tong_so_cau");

                    b.HasKey("Id");

                    b.HasIndex("MaMon");

                    b.HasIndex("NguoiTao");

                    b.ToTable("ngan_hang_de");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NguoiDung", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<long?>("MaVaiTro")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_vai_tro");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<bool>("TrangThai")
                        .HasColumnType("bit")
                        .HasColumnName("trang_thai");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MaVaiTro");

                    b.ToTable("nguoi_dung");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "admin@gmail.com",
                            HoTen = "Quản trị viên",
                            MaVaiTro = 1L,
                            MatKhau = "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92",
                            NgayTao = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TrangThai = true
                        });
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NhatKyViPham", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("LanCuoiXayRa")
                        .HasColumnType("datetime2")
                        .HasColumnName("lan_cuoi_xay_ra");

                    b.Property<string>("LoaiViPham")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_vi_pham");

                    b.Property<long?>("MaBaiThi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_bai_thi");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_tao");

                    b.Property<int>("SoLanViPham")
                        .HasColumnType("int")
                        .HasColumnName("so_lan_vi_pham");

                    b.HasKey("Id");

                    b.HasIndex("MaBaiThi");

                    b.ToTable("nhat_ky_vi_pham");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.PhanCongGiamSat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("MaGiamThi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_giam_thi");

                    b.Property<long?>("MaKyThi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_ky_thi");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_phan_cong");

                    b.HasKey("Id");

                    b.HasIndex("MaGiamThi");

                    b.HasIndex("MaKyThi");

                    b.ToTable("phan_cong_giam_sat");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.PhanCongGiangDay", b =>
                {
                    b.Property<long>("MaLop")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_lop")
                        .HasColumnOrder(0);

                    b.Property<long>("MaMon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_mon")
                        .HasColumnOrder(1);

                    b.Property<long?>("MaGiangVien")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_giang_vien");

                    b.Property<DateTime>("NgayPhanCong")
                        .HasColumnType("datetime2")
                        .HasColumnName("ngay_phan_cong");

                    b.HasKey("MaLop", "MaMon");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaMon");

                    b.ToTable("phan_cong_giang_day");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.TraLoiBaiThi", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool?>("DungHaySai")
                        .HasColumnType("bit")
                        .HasColumnName("dung_hay_sai");

                    b.Property<long?>("MaBaiThi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_bai_thi");

                    b.Property<long?>("MaCauHoi")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_cau_hoi");

                    b.Property<long?>("MaLuaChon")
                        .HasColumnType("bigint")
                        .HasColumnName("ma_lua_chon");

                    b.Property<DateTime?>("ThoiGianTraLoi")
                        .HasColumnType("datetime2")
                        .HasColumnName("thoi_gian_tra_loi");

                    b.HasKey("Id");

                    b.HasIndex("MaBaiThi");

                    b.HasIndex("MaCauHoi");

                    b.HasIndex("MaLuaChon");

                    b.ToTable("tra_loi_bai_thi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.VaiTro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ten_vai_tro");

                    b.HasKey("Id");

                    b.ToTable("vai_tro");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            MoTa = "Quản trị viên hệ thống",
                            TenVaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            MoTa = "Giảng viên quản lý câu hỏi và đề thi",
                            TenVaiTro = "Giảng viên"
                        },
                        new
                        {
                            Id = 3L,
                            MoTa = "Sinh viên tham gia thi",
                            TenVaiTro = "Sinh viên"
                        });
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.BaiThi", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.KyThi", "KyThi")
                        .WithMany("BaiThis")
                        .HasForeignKey("MaKyThi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhanMemThiTracNghiem.Models.NguoiDung", "SinhVien")
                        .WithMany("BaiThis")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("KyThi");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.CauHoiThi", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.MonHoc", "MonHoc")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhanMemThiTracNghiem.Models.NguoiDung", "NguoiDung")
                        .WithMany("CauHoiThis")
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.CauTrucDe", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.MonHoc", "MonHoc")
                        .WithMany("CauTrucDes")
                        .HasForeignKey("MaMon");

                    b.HasOne("PhanMemThiTracNghiem.Models.NganHangDe", "NganHangDe")
                        .WithMany("CauTrucDes")
                        .HasForeignKey("MaNganHangDe")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("MonHoc");

                    b.Navigation("NganHangDe");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.KyThi", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.LopHoc", "LopHoc")
                        .WithMany("KyThis")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhanMemThiTracNghiem.Models.NganHangDe", "NganHangDe")
                        .WithMany("KyThis")
                        .HasForeignKey("MaNganHangDe")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LopHoc");

                    b.Navigation("NganHangDe");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LopHocSinhVien", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.LopHoc", "LopHoc")
                        .WithMany("LopHocSinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhanMemThiTracNghiem.Models.NguoiDung", "SinhVien")
                        .WithMany("LopHocSinhViens")
                        .HasForeignKey("MaSinhVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LuaChonTracNghiem", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.CauHoiThi", "CauHoiThi")
                        .WithMany("LuaChonTracNghiems")
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("CauHoiThi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NganHangDe", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.MonHoc", "MonHoc")
                        .WithMany("NganHangDes")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhanMemThiTracNghiem.Models.NguoiDung", "NguoiDung")
                        .WithMany("NganHangDes")
                        .HasForeignKey("NguoiTao")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MonHoc");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NguoiDung", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.VaiTro", "VaiTro")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaVaiTro")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NhatKyViPham", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.BaiThi", "BaiThi")
                        .WithMany("NhatKyViPhams")
                        .HasForeignKey("MaBaiThi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("BaiThi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.PhanCongGiamSat", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.NguoiDung", "GiamThi")
                        .WithMany("PhanCongGiamSats")
                        .HasForeignKey("MaGiamThi")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhanMemThiTracNghiem.Models.KyThi", "KyThi")
                        .WithMany("PhanCongGiamSats")
                        .HasForeignKey("MaKyThi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("GiamThi");

                    b.Navigation("KyThi");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.PhanCongGiangDay", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.NguoiDung", "GiangVien")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PhanMemThiTracNghiem.Models.LopHoc", "LopHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhanMemThiTracNghiem.Models.MonHoc", "MonHoc")
                        .WithMany("PhanCongGiangDays")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.TraLoiBaiThi", b =>
                {
                    b.HasOne("PhanMemThiTracNghiem.Models.BaiThi", "BaiThi")
                        .WithMany("TraLoiBaiThis")
                        .HasForeignKey("MaBaiThi")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PhanMemThiTracNghiem.Models.CauHoiThi", "CauHoiThi")
                        .WithMany("TraLoiBaiThis")
                        .HasForeignKey("MaCauHoi")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("PhanMemThiTracNghiem.Models.LuaChonTracNghiem", "LuaChonTracNghiem")
                        .WithMany("TraLoiBaiThis")
                        .HasForeignKey("MaLuaChon")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("BaiThi");

                    b.Navigation("CauHoiThi");

                    b.Navigation("LuaChonTracNghiem");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.BaiThi", b =>
                {
                    b.Navigation("NhatKyViPhams");

                    b.Navigation("TraLoiBaiThis");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.CauHoiThi", b =>
                {
                    b.Navigation("LuaChonTracNghiems");

                    b.Navigation("TraLoiBaiThis");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.KyThi", b =>
                {
                    b.Navigation("BaiThis");

                    b.Navigation("PhanCongGiamSats");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LopHoc", b =>
                {
                    b.Navigation("KyThis");

                    b.Navigation("LopHocSinhViens");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.LuaChonTracNghiem", b =>
                {
                    b.Navigation("TraLoiBaiThis");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.MonHoc", b =>
                {
                    b.Navigation("CauHoiThis");

                    b.Navigation("CauTrucDes");

                    b.Navigation("NganHangDes");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NganHangDe", b =>
                {
                    b.Navigation("CauTrucDes");

                    b.Navigation("KyThis");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiThis");

                    b.Navigation("CauHoiThis");

                    b.Navigation("LopHocSinhViens");

                    b.Navigation("NganHangDes");

                    b.Navigation("PhanCongGiamSats");

                    b.Navigation("PhanCongGiangDays");
                });

            modelBuilder.Entity("PhanMemThiTracNghiem.Models.VaiTro", b =>
                {
                    b.Navigation("NguoiDungs");
                });
#pragma warning restore 612, 618
        }
    }
}
